### ISSUE TITLE
'init(red:green:blue:alpha:)' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by eiiot** [richwolf/transit#1]
When I attempt to compile the documentation for Transit with `Product -> Build Documentation`, I get an error in `String+Substring.swift`

`'init(red:green:blue:alpha:)' is only available in iOS 13.0 or newer`

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/39346975/178582347-160661ce-9ce3-4b30-a8e5-9cb6897c67f6.png">

Please let me know if you need any help recreating the issue.

**Comment by richwolf** [comment]
Hi Eliot ... I apologize that this isn't fixed in main. I'll try to have more discipline about making sure that the main branch builds without error going forward (and also fix that error). There is a branch (scratch/current-ideas) that has a fix for the error you found. If you build Transit from that branch, it will work for all platforms, including macOS. It will also generate DocC successfully.

**Comment by richwolf** [comment]
Eliot, I think this should be fixed now in main. Please let me know if I goofed and it's still not letting you build documentation (such as it is for now 😃 ).
